import Head from "next/head";
import React from "react";
import SinglePost from "../../../components/Blog/SinglePost";
import Pagination from "../../../components/Pagination/Pagination";
import { getAllPublished } from "../../../lib/notion";

export const getStaticPaths = async () => {
  const posts = await getAllPublished();
  //   const paths = posts.map(({ slug }) => ({ params: { slug } }));
  //   console.log(paths);

  return {
    // paths: [`/posts/page/1`], // /posts/page/1
    paths: [{ params: { page: "1" } }],
    fallback: "blocking",
  };
};

export const getStaticProps = async () => {
  const data = await getAllPublished(); //ブログ総数の取得のため

  return {
    props: {
      posts: data,
    },
    revalidate: 60, //60s毎にISR発動
  };
};

const BlogPageList = ({ posts }) => {
  return (
    <div className="container h-full w-full mx-auto font-Zen">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="contianer w-full mt-16">
        <h1 className="text-5xl text-dark-100 mb-16 text-center font-medium">
          Notion Blog
        </h1>
        {/* page番号に応じて内容を変える */}
        <section className="sm:grid grid-cols-2 gap-3 w-5/6 mx-auto">
          {posts.map((post, index) => (
            <div className="block" key={index}>
              <SinglePost
                slug={post.slug}
                title={post.title}
                date={post.date}
                description={post.description}
                isPageList={true}
              />
            </div>
          ))}
        </section>
        <Pagination totalCount={10} />
      </main>
      {/* <Pagination totalCount={posts.length} /> */}
    </div>
  );
};

export default BlogPageList;
