import Head from "next/head";
import Link from "next/link";
import React from "react";
import SinglePost from "../../../components/Blog/SinglePost";
import Pagination from "../../../components/Pagination/Pagination";
import {
  getAllPosts,
  getAllTags,
  getNumberOfPages,
  getPostsByPage,
  getPostsByTag,
} from "../../../lib/notion";
import { NUMBER_OF_POSTS_PER_PAGE } from "../../../src/server_constants";

//https://github.com/otoyo/astro-notion-blog/blob/main/src/pages/blog/tag/%5Btag%5D.astro

export const getStaticPaths = async () => {
  const allTags = await getAllTags();
  const paths = allTags.map((tag) => ({ params: { tag: tag } }));
  // console.log(paths);

  return {
    paths,
    fallback: "blocking",
  };
};

export const getStaticProps = async (context) => {
  //何ページ目の記事を持ってくるのか
  const currentTag = context.params?.tag;

  const tagPosts = await getPostsByTag(
    currentTag.toString(),
    NUMBER_OF_POSTS_PER_PAGE
  );

  return {
    props: {
      currentTag: currentTag.toString(),
      posts: tagPosts,
    },
    revalidate: 60, //60s毎にISR発動
  };
};

const BlogTagList = ({ posts, currentPage, numberOfPages, currentTag }) => {
  return (
    <div className="container h-full w-full mx-auto font-Zen">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="contianer w-full mt-16">
        <h1 className="text-5xl text-dark-100 mb-8 text-center font-medium">
          Notion Blog🚀
        </h1>
        <div className="text-center">
          <h3 className="text-white bg-gray-500 px-3 pb-1 rounded-lg inline-block text-2xl text-dark-100 mb-8 text-center font-medium">
            {currentTag}
          </h3>
        </div>
        {/* page番号に応じて内容を変える */}
        <section className="sm:grid grid-cols-2 gap-3 w-5/6 mx-auto">
          {/* /tag/○○の記事だけを取得 */}
          {posts.map((post, index) => (
            <div className="block" key={index}>
              <SinglePost
                slug={post.slug}
                title={post.title}
                date={post.date}
                description={post.description}
                tag={post.tags}
                isPageList={true}
              />
            </div>
          ))}
        </section>
        <Pagination
          currentPage={1}
          numberOfPage={numberOfPages}
          tag={currentTag.toString()} //ここを動的に変更
        />
      </main>
    </div>
  );
};

export default BlogTagList;
