import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import SinglePost from "../components/Blog/SinglePost";
import { getAllPublished } from "../lib/notion";
import styles from "../styles/Home.module.css";

//nextjs + typescript
//https://mo-gu-mo-gu.com/create-next-app-typescript/

//notion custom
//https://bejamas.io/blog/how-to-create-next-js-blog-using-notion-as-a-cms/

// https://www.craftz.dog/

export const getStaticProps = async () => {
  const data = await getAllPublished();

  return {
    props: {
      posts: data,
    },
    revalidate: 60, //60s毎にISR発動
  };
};

export default function Home({ posts }) {
  if (!posts) return <h1>No posts</h1>;

  return (
    <div className="container h-full w-full mx-auto font-Zen">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="contianer w-full mt-16">
        <h1 className="text-5xl text-dark-100 mb-20 text-center font-medium">
          Notion Blog
        </h1>
        {posts.map((post, index) => (
          <div className="mx-4 block">
            <SinglePost
              key={index}
              slug={post.slug}
              title={post.title}
              date={post.date}
              description={post.description}
            />
          </div>
        ))}
      </main>
    </div>
  );
}
