import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import SinglePost from "../components/Blog/SinglePost";
import Pagination from "../components/Pagination/Pagination";
import Tag from "../components/Tag/Tag";
import { getAllPosts, getAllTags, getPosts } from "../lib/notion";
import styles from "../styles/Home.module.css";

//nextjs + typescript
//https://mo-gu-mo-gu.com/create-next-app-typescript/

//notion custom
//https://bejamas.io/blog/how-to-create-next-js-blog-using-notion-as-a-cms/
//https://github.com/otoyo/astro-notion-blog/blob/main/src/lib/notion/client.ts

// https://www.craftz.dog/
// https://www.nbr41.com/posts
// https://zenn.dev/nbr41to/articles/474df7540c475c

// https://alpacat.com/

export const getStaticProps = async () => {
  const data = await getPosts();
  const allTags = await getAllTags();

  return {
    props: {
      posts: data,
      allTags,
    },
    revalidate: 60, //60s毎にISR発動
  };
};

export default function Home({ posts, allTags }) {
  if (!posts) return <h1>No posts</h1>;

  return (
    <div className="container h-full w-full mx-auto font-Zen">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="contianer w-full mt-16">
        <h1 className="text-5xl text-dark-100 mb-16 text-center font-medium">
          Notion Blog🚀
        </h1>
        {/* 4つだけ表示させたい */}
        {posts.map((post, index) => (
          <div className="mx-4 block" key={index}>
            <SinglePost
              slug={post.slug}
              title={post.title}
              date={post.date}
              description={post.description}
              tag={post.tags}
              isPageList={false}
            />
          </div>
        ))}
        <Link
          href="/posts/page/1"
          className="mb-6 lg:w-1/2 mx-auto rounded-md px-5 block text-right"
        >
          ...もっと見る
        </Link>
        <Tag tags={allTags} />
      </main>
    </div>
  );
}
